[project]
name = "artemis"
version = "0.1.0"
description = "Mapeamento de notícias de feminicídio"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "apache-airflow>=3.2.1",
    "apache-airflow-providers-docker>=4.5.5",
    "apache-airflow-providers-standard>=1.13.0",
    "confluent-kafka>=2.14.0",
    "dotenv>=0.9.9",
    "great-expectations>=1.17.2",
    "httpx>=0.28.1",
    "minio>=7.2.20",
    "ollama",
    "paramiko==3.0",
    "pre-commit>=4.6.0",
    "psycopg2-binary>=2.9.12",
    "pyaml>=26.2.1",
    "pydantic>=2.13.4",
    "pymongo>=4.17.0",
    "pytest>=9.0.3",
    "pytz>=2026.2",
    "ruff>=0.15.13",
    "scrapy==2.11.1",
    "scrapy-playwright>=0.0.46",
    "sshtunnel>=0.4.0",
    "testcontainers>=4.14.2",
    "unidecode>=1.4.0",
]

[tool.ruff]
line-length = 95

select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
