KEYWORDS = {
    'ACAO_VIOLENTA': [
        'agredida', 
        'agressao', 
        'asfixiada', 
        'assassinada', 
        'assassinato', 
        'baleada', 
        'carbonizada', 
        'crime passional', 
        'esfaqueada', 
        'espancada', 
        'estrangulada', 
        'feminicidio', 
        'matou', 
        'morta', 
        'morte', 
        'motivo futil',
        'tentativa de feminicidio', 
        'violencia contra a mulher', 
        'violencia domestica',
        'violencia de genero'
    ],
    'AGRESSOR': [
        'agressor', 
        'amante', 
        'autor do crime', 
        'companheiro', 
        'esposo', 
        'ex-companheiro', 
        'ex-esposo', 
        'ex-marido', 
        'ex-namorado', 
        'ex-noivo', 
        'ex-parceiro',
        'marido', 
        'namorado', 
        'noivo', 
        'parceiro', 
        'suspeito'
    ]
}

VALIDATION_KEYWORDS = {
    'ACAO_VIOLENTA': [
        r'\bagredidas?\b', 
        r'\bagress(?:ao|oes)\b', 
        r'\basfixiadas?\b', 
        r'\bassassinadas?\b', 
        r'\bassassinatos?\b', 
        r'\bbaleadas?\b', 
        r'\bcarbonizadas?\b', 
        r'\bcrime\s*passional\b', 
        r'\besfaqueadas?\b', 
        r'\bespancadas?\b', 
        r'\bestranguladas?\b', 
        r'\bfeminic[ií]dios?\b', 
        r'\bmatou\b', 
        r'\bmortas?\b', 
        r'\bmortes?\b', 
        r'\bmotivo\s*f[uú]til\b',
        r'\btentativas?\s*de\s*feminic[ií]dio\b', 
        r'\bviol[eê]ncia\s*contra\s*a\s*mulher\b', 
        r'\bviol[eê]ncia\s*dom[eé]stica\b',
        r'\bviol[eê]ncia\s*de\s*g[eê]nero\b'
    ],
    'AGRESSOR': [
        r'\bagressores?\b', 
        r'\bamantes?\b', 
        r'\bautores?\s*(?:do\s*crime)?\b', 
        r'\bcompanheiros?\b', 
        r'\besposos?\b', 
        r'\bex-companheiros?\b', 
        r'\bex-esposos?\b', 
        r'\bex-maridos?\b', 
        r'\bex-namorados?\b', 
        r'\bex-noivos?\b', 
        r'\bex-parceiros?\b',
        r'\bmaridos?\b', 
        r'\bnamorados?\b', 
        r'\bnoivos?\b', 
        r'\bparceiros?\b', 
        r'\bsuspeitos?\b'
    ]
}