KEYWORDS = {
    'AGRESSOR': [
        'agressor', 'amante', 'autor do crime', 'companheiro', 'esposo', 
        'ex-companheiro', 'ex-esposo', 'ex-marido', 'ex-namorado', 'ex-noivo', 
        'ex-parceiro', 'marido', 'namorado', 'noivo', 'parceiro', 'suspeito',
        'padrasto', 'pai', 'irmão', 'tio', 'primo', 'ex', 'atual', 
        'conjugê', 'homem', 'acusado', 'indiciado', 'investigado', 'algoz'
    ],
    
    'ACAO_VIOLENTA': [
        'agressao', 'assassinato', 'crime passional', 'feminicidio', 'morte', 
        'motivo futil', 'tentativa de feminicidio', 'violencia contra a mulher', 
        'violencia domestica', 'violencia de genero', 'crime de genero',
        'homicidio qualificado', 'disparos', 'golpes de faca', 'violencia sexual', 
        'abuso', 'lesao corporal', 'ameaca', 'medida protetiva', 
        'assassina', 'mata', 'esfaqueia', 'atira', 'agride', 'espanca', 'asfixia', 
        'estrangula', 'carboniza', 'executa', 'golpeia', 'ataca', 'ameaça',
        'assassinou', 'matou', 'esfaqueou', 'atirou', 'agrediu', 'espancou',
        'asfixiou', 'encontrada morta', 'degolada', 'esganada',
        'estrangulou', 'carbonizou', 'executou', 'golpeou', 'atacou', 'ameaçou',
        'agredida', 'asfixiada', 'assassinada', 'baleada', 'carbonizada', 
        'esfaqueada', 'espancada', 'estrangulada', 'morta', 'executada', 
    ],
}

VALIDATION_KEYWORDS = {
    'AGRESSOR': [
        r'\bagressores?\b', 
        r'\bamantes?\b', 
        r'\bautores?\s*(?:do\s*crime)?\b', 
        r'\bcompanheiros?\b', 
        r'\besposos?\b', 
        r'\bex-companheiros?\b', 
        r'\bex-esposos?\b', 
        r'\bex-maridos?\b', 
        r'\bex-namorados?\b', 
        r'\bex-noivos?\b', 
        r'\bex-parceiros?\b',
        r'\bmaridos?\b', 
        r'\bnamorados?\b', 
        r'\bnoivos?\b', 
        r'\bparceiros?\b', 
        r'\bsuspeitos?\b',
        r'\bpadrastos?\b',
        r'\bpais?\b',
        r'\birm[aã]os?\b',
        r'\btios?\b',
        r'\bprimos?\b',
        r'\bex\b',
        r'\batual\b',
        r'\bc[oó]njuges?\b',
        r'\bhomens?\b',
        r'\bacusados?\b',
        r'\bindiciados?\b',
        r'\binvestigados?\b',
        r'\balgoz(?:es)?\b'
    ],
    
    'ACAO_VIOLENTA': [
        r'\bagredidas?\b', 
        r'\bagress(?:ao|oes)\b', 
        r'\basfixiadas?\b', 
        r'\bassassinadas?\b', 
        r'\bassassinatos?\b', 
        r'\bbaleadas?\b', 
        r'\bcarbonizadas?\b', 
        r'\bcrime\s*passional\b', 
        r'\besfaqueadas?\b', 
        r'\bespancadas?\b', 
        r'\bestranguladas?\b', 
        r'\bfeminic[ií]dios?\b', 
        r'\bmatou\b', 
        r'\bmortas?\b', 
        r'\bmortes?\b', 
        r'\bmotivo\s*f[uú]til\b',
        r'\btentativas?\s*de\s*feminic[ií]dio\b', 
        r'\bviol[eê]ncia\s*contra\s*a\s*mulher\b', 
        r'\bviol[eê]ncia\s*dom[eé]stica\b',
        r'\bviol[eê]ncia\s*de\s*g[eê]nero\b',
        r'\bcrime\s*de\s*g[eê]nero\b',
        r'\bhomic[ií]dios?\s*qualificados?\b',
        r'\bdisparos?\b',
        r'\bgolpes?\s*de\s*faca\b',
        r'\bviol[eê]ncia\s*sexual\b',
        r'\babusos?\b',
        r'\bles(?:ao|oes)\s*corporal\b',
        r'\bamea[cç]as?\b',
        r'\bmedidas?\s*protetivas?\b',
        r'\bassassina\b',
        r'\bmata\b',
        r'\besfaqueia\b',
        r'\batira\b',
        r'\bagride\b',
        r'\bespanca\b',
        r'\basfixia\b',
        r'\bestrangula\b',
        r'\bcarboniza\b',
        r'\bexecuta\b',
        r'\bgolpeia\b',
        r'\bataca\b',
        r'\bamea[cç]a\b',
        r'\bassassinou\b',
        r'\besfaqueou\b',
        r'\batirou\b',
        r'\bagrediu\b',
        r'\bespancou\b',
        r'\basfixiou\b',
        r'\bestrangulou\b',
        r'\bcarbonizou\b',
        r'\bexecutou\b',
        r'\bgolpeou\b',
        r'\batacou\b',
        r'\bamea[cç]ou\b',
        r'\bexecutadas?\b',
        r'\bencontradas?\s*mortas?\b',
        r'\bdegoladas?\b',
        r'\besganadas?\b'
    ]
}